### PR TITLE
IOS-13679: Janrain iOS8 deprecation

### PR DESCRIPTION
**Pull request by Harinder**
##### Description
- Update to latest (5.0.4) Janrain library
- iOS8 deprecation from janrain library

##### JIRA issue(s)
https://jira.corp.docusign.com/browse/IOS-13679

##### Reviewers
@thomas-dang , please review this PR

### CODE REVIEW

**Comment by Harinder** [comment]
@thomas-dang, can we merge this?

**Comment by Harinder** [comment]
@thomas-dang, can we close this? We have a seperate Jump.iOS repo now

**Comment by Harinder** [comment]
@thomas-dang, can we close this?

**Comment by thomas-dang** [comment]
Closing this pull request as we have moved over to the updated https://github.com/DocuSignDev/jump.ios repo.

**Pull request closed without merging**
